steps:
- name: node:14.15.1
  entrypoint: yarn
  args: ["run", "create-env"]
  env:
    - 'BOT_COMMAND_PREFIX=${_COMMAND_PREFIX}'
    - 'BOT_DISCORD_TOKEN=${_DISCORD_TOKEN}'
    - 'BOT_DATA_QUOTES=${_DATA_QUOTES}'
    - 'BOT_DATA_REACTIONS=${_DATA_REACTIONS}'
    - 'BOT_DATA_CRONTAB=${_DATA_CRONTAB}'

- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/dotintegral/botintegral:$SHORT_SHA", "."]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/dotintegral/botintegral:$SHORT_SHA"]

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=kubernetes-resource-file
#   - --image=gcr.io/dotintegral/botintegral:$SHORT_SHA
#   - --location=location
#   - --cluster=cluster