steps:
- name: "gcr.io/cloud-builders/docker"
  env:
  args: ["build", 
    "-t", "gcr.io/dotintegral/botintegral:$SHORT_SHA",
    "--env", "COMMAND_PREFIX=${_COMMAND_PREFIX}",
    "--env", "DISCORD_TOKEN=${_DISCORD_TOKEN}",
    "--env", "DATA_QUOTES=${_DATA_QUOTES}",
    "--env", "DATA_QUOTES=${_DATA_QUOTES}",
    "--env", "DATA_CRONTAB=${_DATA_CRONTAB}",
    "."
    ]

- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/dotintegral/botintegral:$SHORT_SHA"]

# - name: "gcr.io/cloud-builders/gke-deploy"
#   args:
#   - run
#   - --filename=kubernetes-resource-file
#   - --image=gcr.io/dotintegral/botintegral:$SHORT_SHA
#   - --location=location
#   - --cluster=cluster