apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-01-12T15:44:07Z"
  generation: 3
  labels:
    app: botintegral
  name: botintegral
  namespace: default
  resourceVersion: "4596"
  selfLink: /apis/apps/v1/namespaces/default/deployments/botintegral
  uid: eeed63db-2bbd-4429-ac20-5dc4584d70f3
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: botintegral
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: botintegral
    spec:
      containers:
      - env:
        - name: TEST_KEY
          valueFrom:
            configMapKeyRef:
              key: TEST_KEY
              name: botintegral-config-jlbv
        image: gcr.io/dotintegral/botintegral@sha256:15321209f386c80d094975bf5b49ed4740a74841aa6e38ae55bf446049f03d73
        imagePullPolicy: IfNotPresent
        name: botintegral-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-01-12T15:44:48Z"
    lastUpdateTime: "2021-01-12T15:44:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-01-12T15:44:07Z"
    lastUpdateTime: "2021-01-12T15:44:48Z"
    message: ReplicaSet "botintegral-7994b85df8" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1