---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "botintegral-config-v1zl"
  namespace: "default"
  labels:
    app: "botintegral"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "botintegral"
  namespace: "default"
  labels:
    app: "botintegral"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "botintegral"
  template:
    metadata:
      labels:
        app: "botintegral"
    spec:
      containers:
      - name: "botintegral-sha256-1"
        image: "gcr.io/dotintegral/botintegral@sha256:fb3e0ea722002f58cf4b4f8a4fe621ec188fb93273709ddc69adefee0ba37ede"
        env:
        - name: "COMMAND_PREFIX"
          valueFrom:
            configMapKeyRef:
              key: "COMMAND_PREFIX"
              name: "botintegral-config-v1zl"